name: Manually Deploy 

jobs:
  deploy:
    runs-on: ubuntu-latest
        with:
          usedocker: true
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
