name: Manually Deploy 

jobs:
  deploy:
    runs-on: ubuntu-latest
        with:
          usedocker: true
          stack: "container"
          region: "us"
        env:
          production_environment: true
